"""
Run from the project root:

    python scripts/run_wsi_pipeline_batch.py

Runs the final WSI preprocessing pipeline for all 15 slides in the
final manifest.

Behavior:
- Keeps the already-final A9KO output.
- Reprocesses every other manifest slide, even if an old .npz exists.
- Removes stale .npz files that do not belong to the final manifest.
- Removes stale figures belonging to slides not in the final manifest.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd

from utils.logging_utils import get_logger
from utils.config import load_config
from wsi_branch.dino_embedding import load_dino
from run_wsi_pipeline import process_one_slide


log = get_logger(__name__)


# This slide was already rerun using the finalized pipeline settings.
FINAL_EXISTING_SLIDES = {
    "TCGA-2F-A9KO-01Z-00-DX1.195576CF-B739-4BD9-B15B-4A70AE287D3E.svs"
}


def find_slide_paths(wsi_root: Path, manifest_path: Path) -> list[Path]:
    """Return all SVS files listed in the final manifest."""
    manifest = pd.read_csv(manifest_path, sep="\t")

    paths = []

    for filename in manifest["filename"]:
        p = wsi_root / filename

        if p.exists():
            paths.append(p)
        else:
            log.info(f"  MISSING: {filename}")

    return paths


def cleanup_stale_outputs(
    manifest_path: Path,
    processed_wsi_dir: Path,
    figures_dir: Path,
):
    """
    Remove outputs that do not correspond to any slide in the final manifest.
    """

    manifest = pd.read_csv(manifest_path, sep="\t")

    expected_stems = {
        Path(filename).stem
        for filename in manifest["filename"]
    }

    log.info("=" * 60)
    log.info("Checking for stale WSI outputs...")

    # ---------------------------------------------------------
    # Remove stale NPZ files
    # ---------------------------------------------------------
    for npz_path in processed_wsi_dir.glob("*_patches.npz"):

        slide_stem = npz_path.name.removesuffix("_patches.npz")

        if slide_stem not in expected_stems:
            log.info(
                f"  Removing stale WSI output: {npz_path.name}"
            )
            npz_path.unlink()

    # ---------------------------------------------------------
    # Remove stale figures
    # ---------------------------------------------------------
    for figure_path in figures_dir.glob("*.png"):

        filename = figure_path.name

        # Only consider figures generated by the WSI pipeline.
        matched_stem = None

        for stem in expected_stems:
            if filename.startswith(stem + "_fig"):
                matched_stem = stem
                break

        # If it looks like a WSI figure but does not belong
        # to one of the final manifest slides, remove it.
        if "_fig" in filename and matched_stem is None:
            log.info(
                f"  Removing stale figure: {filename}"
            )
            figure_path.unlink()

    log.info("Stale-output cleanup complete.")


def main():

    cfg = load_config()
    wcfg = cfg["wsi_branch"]

    figures_dir = Path(cfg["paths"]["figures_dir"])
    figures_dir.mkdir(parents=True, exist_ok=True)

    out_dir = Path(cfg["paths"]["processed_wsi_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = Path(cfg["paths"]["manifest"])
    wsi_root = Path(cfg["paths"]["wsi_root"])

    # ---------------------------------------------------------
    # Find final manifest slides
    # ---------------------------------------------------------
    slide_paths = find_slide_paths(
        wsi_root,
        manifest_path
    )

    log.info(
        f"Found {len(slide_paths)} slides from final manifest"
    )

    # ---------------------------------------------------------
    # Clean outputs that don't belong to final manifest
    # ---------------------------------------------------------
    cleanup_stale_outputs(
        manifest_path,
        out_dir,
        figures_dir
    )

    # ---------------------------------------------------------
    # Load DINO once
    # ---------------------------------------------------------
    checkpoint = None

    if "dino_training" in cfg:

        default_ckpt = (
            Path(cfg["dino_training"]["checkpoint_dir"])
            / f"{wcfg['dino_model']}_mini_latest.pt"
        )

        if default_ckpt.exists():
            checkpoint = str(default_ckpt)

    model, device = load_dino(
        wcfg["dino_repo"],
        wcfg["dino_model"],
        checkpoint_path=checkpoint
    )

    log.info(
        f"DINO loaded once "
        f"({'trained checkpoint' if checkpoint else 'ImageNet pretrained'}), "
        f"reused for all slides."
    )

    # ---------------------------------------------------------
    # Process slides
    # ---------------------------------------------------------
    succeeded = []
    failed = []
    skipped = []

    for i, slide_path in enumerate(slide_paths, 1):

        log.info("=" * 60)
        log.info(
            f"=== Slide {i}/{len(slide_paths)}: "
            f"{slide_path.name} ==="
        )

        # A9KO has already been processed using the final
        # finalized pipeline settings.
        if slide_path.name in FINAL_EXISTING_SLIDES:

            expected_output = (
                out_dir /
                f"{slide_path.stem}_patches.npz"
            )

            if expected_output.exists():

                log.info(
                    "  SKIPPED — already processed with final settings."
                )

                skipped.append(slide_path.name)
                continue

            else:
                log.info(
                    "  Final output missing — processing A9KO."
                )

        # -----------------------------------------------------
        # All other manifest slides are ALWAYS reprocessed.
        # -----------------------------------------------------
        try:

            process_one_slide(
                slide_path,
                cfg,
                wcfg,
                model,
                device,
                figures_dir,
                out_dir
            )

            succeeded.append(slide_path.name)

        except Exception as exc:

            log.info(
                f"  FAILED: {slide_path.name} — {exc}"
            )

            failed.append(
                (slide_path.name, str(exc))
            )

    # ---------------------------------------------------------
    # Final summary
    # ---------------------------------------------------------
    log.info("=" * 60)
    log.info("FINAL WSI BATCH SUMMARY")
    log.info("=" * 60)

    log.info(
        f"Manifest slides: {len(slide_paths)}"
    )

    log.info(
        f"Processed successfully: {len(succeeded)}"
    )

    log.info(
        f"Skipped (already final): {len(skipped)}"
    )

    log.info(
        f"Failed: {len(failed)}"
    )

    if skipped:
        log.info("\nSkipped:")
        for name in skipped:
            log.info(f"  {name}")

    if failed:
        log.info("\nFAILED:")
        for name, err in failed:
            log.info(f"  {name}: {err}")


if __name__ == "__main__":
    main()